tap "homebrew/bundle"
tap "homebrew/core"
brew "cmake"
brew "cmatrix"
brew "fzf"
brew "googler"
brew "macvim", link: false
brew "neomutt"
brew "ranger"
brew "ripgrep"
brew "translate-shell"
brew "tree"
brew "vim"
brew "zsh"
